"""Labeler configuration generator and parser for actions/labeler."""
from typing import Dict, List, Any
import re

DEFAULT_TIMEOUT_SECONDS = 30
timeout=DEFAULT_TIMEOUT_SECONDS

DEFAULT_LABEL_RULES: Dict[str, List[str]] = {
    "documentation": ["docs/**", "**/*.md", "specs/**"],
    "backend": ["core/**", "src/**", "app/**", "**/*.py", "**/*.go", "**/*.rs"],
    "frontend": ["web/**", "static/**", "templates/**", "**/*.js", "**/*.ts", "**/*.html", "**/*.css"],
    "ci-cd": [".github/workflows/**", "Dockerfile", "docker-compose*.yml"],
    "tests": ["tests/**", "spec/**", "**/*test*.py"]
}

def generate_labeler_config(custom_rules: Dict[str, List[str]] = None) -> str:
    rules = dict(DEFAULT_LABEL_RULES)
    if custom_rules:
        rules.update(custom_rules)

    lines = [
        "# .github/labeler.yml - Generated by tool-triage-flow-automator",
        "# Declarative path-based pull request labeler configuration (v5 format)",
        ""
    ]

    for label, patterns in sorted(rules.items()):
        lines.append(f"{label}:")
        lines.append("  - changed-files:")
        lines.append("      - any-glob-to-any-file:")
        for pat in patterns:
            lines.append(f"          - '{pat}'")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"
